### PR TITLE
Updated less dependency for Meteor 1.2 (also backcompat)

### PR DESCRIPTION
**Pull request by CaptainN**
I updated the less dependency so that it will work with Meteor 1.2, also kept Meteor less than 1.2 working.

### CODE REVIEW

**Comment by jackkav** [comment]
+1

**Comment by kristijanbambir** [comment]
+1

**Comment by davidmoret** [comment]
+1

**Comment by abernix** [comment]
:+1:

**Comment by HosseinAgha** [comment]
+1

**Comment by ekuiter** [comment]
+1

**Comment by jwktje** [comment]
+1

**Comment by Kostanos** [comment]
+1

**Comment by TimoRuetten** [comment]
+1

**Comment by quackware** [comment]
+1

**Comment by FreedCapybara** [comment]
+1

**Comment by jwktje** [comment]
Awesome! Thanks @mpowaga

**Comment by mpowaga** [comment]
@jwktje As soon as @yogiben finds time to do it :)

**Pull request merged**
