### PR TITLE
Updated aldeed:autoform@5.0.0

### PR DESCRIPTION
**Pull request by raedle**
Updated to aldeed:autofrom@5.0.0.
Only tested it with my projects. Everything works as before.

### CODE REVIEW

**Comment by tcastelli** [comment]
+1 for integration

**Comment by etmarch** [comment]
+1 as well

**Comment by andrefgneves** [comment]
+1

**Comment by Alveoli** [comment]
+1 please

**Comment by Benczyk** [comment]
+1 please

**Comment by abernix** [comment]
+1

**Pull request closed without merging**
