### PR TITLE
absoluteSrc, autosave, autoform 5.0.0

### PR DESCRIPTION
**Pull request by jfols**

### CODE REVIEW

**Comment by mpowaga** [comment]
@jfols What's the advantage of using `Meteor.absoluteUrl` over `href="/url-here"`? Frankly I don't see any. Anyway great idea with `download` attribute and autosave feature.

**Comment by jfols** [comment]
One advantage is if the form is rendered/sent somewhere outside the context of the Meteor app, in my case an email that contains form submissions--a relative link would go somewhere like `gmail.com/url-here`

**Comment by mpowaga** [comment]
That makes sense. Do we need try-catch block?

**Comment by jfols** [comment]
Probably not, sorry didn't clean that up.

**Comment by jfols** [comment]
closing due to age and inactivity

**Pull request closed without merging**
